
load("C:/Users/juanc/Desktop/R Practicas/Practica 1/Datos_personas.RData")
Datos_personas$IMC <- with(Datos_personas, Peso/Altura^2)
load("C:/Users/juanc/Desktop/R Practicas/RCars.RData")
Consumos_Europa <- subset(RCars, subset=origen=="Europa", select=c(consumo))
names(Consumos_Europa)
summary(Consumos_Europa)
Consumos_Japon <- subset(RCars, subset=origen=="Japon", select=c(consumo))
summary(Consumos_Japon)
cil_no_8 <- subset(RCars, subset=cilindr!=8, select=c(cv))
summary(cil_no_8)
summary(cil_no_8)
summary(RCars)
RCars <- within(RCars, {
  cilindr_fac <- as.factor(cilindr)
})
summary(RCars)
library(abind, pos=25)
library(e1071, pos=26)
numSummary(RCars[,"cilindr", drop=FALSE], statistics=c("mean", "sd", "IQR", "quantiles"), quantiles=c(0,.25,.5,.75,1))
summary(RCars)
names(RCars)
editDataset(RCars)
numSummary(RCars[,c("cv", "peso"), drop=FALSE], groups=RCars$origen, statistics=c("mean", "quantiles"), quantiles=c(0,.25,0.3,.5,.75,1))
numSummary(RCars[,c("cv", "peso"), drop=FALSE], groups=RCars$cilindr_fac, statistics=c("mean", "quantiles"), quantiles=c(0,.25,0.3,.5,.75,1))
numSummary(RCars[,"acel", drop=FALSE], groups=RCars$cilindr_fac, statistics=c("sd", "var", "quantiles"), quantiles=c(0,.25,0.3,.5,.75,1))
numSummary(RCars[,"acel", drop=FALSE], groups=RCars$cilindr_fac, statistics=c("sd", "quantiles"), quantiles=c(0,.25,0.3,.5,.75,1))
numSummary(RCars[,"acel", drop=FALSE], groups=RCars$cilindr_fac, statistics=c("mean", "sd", "quantiles"), quantiles=c(0,.25,0.3,.5,.75,1))
numSummary(RCars[,"acel", drop=FALSE], groups=RCars$cilindr_fac, statistics=c("sd", "quantiles"), quantiles=c(0,.25,0.3,.5,.75,1))
var(RCars$acel,na.rm=TRUE)
numSummary(RCars[,"peso", drop=FALSE], groups=RCars$origen, statistics=c("quantiles", "skewness", "kurtosis"), quantiles=c(0,.25,0.3,.5,.75,1), type="1")
Tapply(consumo ~ cilindr_fac + origen, mean, na.action=na.omit, data=RCars) # mean by groups
Tapply(consumo ~ cilindr_fac + origen, sd, na.action=na.omit, data=RCars) # sd by groups
Tapply(consumo ~ cilindr_fac + origen, median, na.action=na.omit, data=RCars) # median by groups
local({
  .Table <- with(RCars, table(origen))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nColumn percentages:\n")
  print(colPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~cilindr_fac+origen, data=RCars)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nRow percentages:\n")
  print(rowPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
library(colorspace, pos=27)
RCars <- within(RCars, {
  peso_fact <- as.factor(peso)
})
with(RCars, piechart(peso_fact, xlab="", ylab="", main="peso_fact", col=rainbow_hcl(318), scale="percent"))
RCars <- within(RCars, {
  peso_rec <- Recode(peso, '225:525="[225,525]"; 525:825="(525,825]"; 825:1125="(825,1125]"; 1125:1425="(1125,1425]"; 1425:1725="(1425,1725]"', as.factor=TRUE, to.value="=", interval=":", separator=";")
})
with(RCars, piechart(peso_rec, xlab="", ylab="", main="peso_rec", col=rainbow_hcl(5), scale="percent"))
with(RCars, piechart(peso_rec, xlab="", ylab="", main="peso_rec", col=rainbow_hcl(5), scale="percent"))
local({
  .Table <- with(RCars, table(peso_rec))
  cat("\ncounts:\n")
  print(.Table)
  cat("\npercentages:\n")
  print(round(100*.Table/sum(.Table), 2))
})
with(RCars, Barplot(origen, xlab="origen", ylab="Frequency", label.bars=TRUE))
with(RCars, Hist(peso, scale="frequency", breaks="Sturges", col="darkgray"))
with(RCars, Hist(peso, scale="percent", breaks="Sturges", col="darkgray"))
with(RCars, Hist(peso, groups=origen, scale="percent", breaks="Sturges", col="darkgray"))
with/RCars,Hist(peso,scale="frequency",breaks="Sturges",col="darkgray"))
with(
with(RCars,Hist(peso,scale="frequency",breaks="Sturges",col="darkgray"))
with(RCars, Hist(motor, scale="frequency", breaks=c(0,2000,4000,6000,8000),col="darkgray"))
RCars <- within(RCars, {
  año_fac <- as.factor(año)
})
with(RCars, plotMeans(cv, año_fac, origen, error.bars="none", connect=TRUE, legend.pos="farright"))
library(lattice, pos=28)
xyplot(consumo ~ peso, type="p", pch=16, auto.key=list(border=TRUE), par.settings=simpleTheme(pch=16), scales=list(x=list(relation='same'), y=list(relation='same')), data=RCars)
xyplot(consumo ~ peso, groups=cilindr_fac, type="p", pch=16, auto.key=list(border=TRUE), par.settings=simpleTheme(pch=16), scales=list(x=list(relation='same'), y=list(relation='same')), data=RCars)
xyplot(consumo ~ peso | origen, groups=cilindr_fac, type="p", pch=16, auto.key=list(border=TRUE), par.settings=simpleTheme(pch=16), scales=list(x=list(relation='same'), y=list(relation='same')), data=RCars)
Boxplot(consumo ~ origen, data=RCars, id=list(method="y"))
library(lpSolve, pos=29)


direccion="max"
vec obj=c(2,1)
mat rest=matrix(c(1,1,1,-2),nrow=2,byrow=TRUE)2
signo rest=c("<=","<=")
vec rec=c(5,3)
solucion=lp(direccion,vec obj,mat rest,signo rest,vec rec,int.vec=var ent)
solucion$objval
solucion$solution
